language: scala
scala:
  - 2.9.3
  - 2.10.6
  - 2.11.11
  - 2.12.2
env:
  global:
    - SECRETKEEPER_AWS_ACCESS_KEY=access_key
    - SECRETKEEPER_AWS_SECRET_KEY=secret_key
    - SECRETKEEPER_AWS_REGION=us-east-1
script:
  - sbt clean coverage test
after_success:
  - sbt coverageReport coveralls
